<a href="https://colab.research.google.com/github/hrushikute/DataAnalytics/blob/master/00Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamentals of tensor flow

In [ ]:
#Import TensorFlow
import tensorflow as tf
print (tf.__version__)


2.5.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check dimension of vector
vector.ndim

1

In [ ]:
# create a matrix
matrix =tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matric
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#number of dimension of another matrix
another_matrix.ndim

2

In [ ]:
# Lets create a tensor

tensor = tf.constant([[[1,2,3],
                       [3,3,4],
                       [1,2,6]
                       ]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 3, 4],
        [1, 2, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
##What we create so far
#* Scalar : a single number
#* Vector : a number with direction (eg : velocity)
#* Matrix : a 2-dimentional array of numbers
#* Tensor : an n-dimenstional array of numbers (where n can be any number 0 dimensional tensor is scalar 1 dimensional  tensor is vector)

In [ ]:
# Create tensor variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10.7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([10.7], dtype=float32)>)

In [ ]:
# Lets try to change the elements in tensor variable
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [ ]:
#try to assign 
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(12)
unchangeable_tensor

AttributeError: ignored

In [ ]:
#Creating random tensors

random_1=tf.random.Generator.from_seed(34)
random_1 = random_1.normal(shape=(3,2))

random_2=tf.random.Generator.from_seed(34)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.5181769 ,  1.4020647 ],
        [ 1.5570306 , -0.96762174],
        [ 0.495291  , -0.648484  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.5181769 ,  1.4020647 ],
        [ 1.5570306 , -0.96762174],
        [ 0.495291  , -0.648484  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.5181769 ,  1.4020647 ],
       [ 0.495291  , -0.648484  ],
       [ 1.5570306 , -0.96762174]], dtype=float32)>

## Getting Information from Tensors

#Shape 
#Rank
#Axis or dimension
#Size


#Create a tensor 

In [ ]:
# Create a rank 4 tensor (4 dimens)
rank4_tensor = tf.zeros(shape=(2,3,4,5))
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank4_tensor.shape, rank4_tensor.ndim, tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)