<a href="https://colab.research.google.com/github/hrushikute/DataAnalytics/blob/master/00Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Fundamentals of tensor flow

In [ ]:
#Import TensorFlow
import tensorflow as tf
print (tf.__version__)


2.5.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
#check dimension of vector
vector.ndim

1

In [ ]:
# create a matrix
matrix =tf.constant([[10,7],
                     [7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matric
another_matrix = tf.constant([[10.,7.],
                              [3.,2.],
                              [8.,9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
#number of dimension of another matrix
another_matrix.ndim

2

In [ ]:
# Lets create a tensor

tensor = tf.constant([[[1,2,3],
                       [3,3,4],
                       [1,2,6]
                       ]])
tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [3, 3, 4],
        [1, 2, 6]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
##What we create so far
#* Scalar : a single number
#* Vector : a number with direction (eg : velocity)
#* Matrix : a 2-dimentional array of numbers
#* Tensor : an n-dimenstional array of numbers (where n can be any number 0 dimensional tensor is scalar 1 dimensional  tensor is vector)

In [ ]:
# Create tensor variable
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10.7])
changeable_tensor, unchangeable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(1,), dtype=float32, numpy=array([10.7], dtype=float32)>)

In [ ]:
# Lets try to change the elements in tensor variable
changeable_tensor[0]=7
changeable_tensor

TypeError: ignored

In [ ]:
#try to assign 
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign(12)
unchangeable_tensor

AttributeError: ignored

In [ ]:
#Creating random tensors

random_1=tf.random.Generator.from_seed(34)
random_1 = random_1.normal(shape=(3,2))

random_2=tf.random.Generator.from_seed(34)
random_2 = random_2.normal(shape=(3,2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.5181769 ,  1.4020647 ],
        [ 1.5570306 , -0.96762174],
        [ 0.495291  , -0.648484  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-1.5181769 ,  1.4020647 ],
        [ 1.5570306 , -0.96762174],
        [ 0.495291  , -0.648484  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
tf.random.shuffle(random_1)

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.5181769 ,  1.4020647 ],
       [ 1.5570306 , -0.96762174],
       [ 0.495291  , -0.648484  ]], dtype=float32)>

## Getting Information from Tensors

#Shape 
#Rank
#Axis or dimension
#Size


#Create a tensor 

In [ ]:
# Create a rank 4 tensor (4 dimens)
rank4_tensor = tf.zeros(shape=(2,3,4,5))
rank4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank4_tensor.shape, rank4_tensor.ndim, tf.size(rank4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Matrix Multiplication 


In [ ]:
print(tensor)

tf.Tensor(
[[[1 2 3]
  [3 3 4]
  [1 2 6]]], shape=(1, 3, 3), dtype=int32)


In [ ]:
tf.matmul(tensor,tensor)

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[10, 14, 29],
        [16, 23, 45],
        [13, 20, 47]]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(1, 3, 3), dtype=int32, numpy=
array([[[10, 14, 29],
        [16, 23, 45],
        [13, 20, 47]]], dtype=int32)>

In [ ]:
#create a tensor of (3,2)
x = tf.constant([[2,5],
                 [6,7],
                 [1,8]])
y = tf.constant([[1,2,1],
                 [0,1,0],
                 [2,3,4]
                ])
x , y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 5],
        [6, 7],
        [1, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 1],
        [0, 1, 0],
        [2, 3, 4]], dtype=int32)>)

In [ ]:
tf.matmul(y,x)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
y @ x

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[15, 27],
       [ 6,  7],
       [26, 63]], dtype=int32)>

In [ ]:
#lets reshape x to (2,3)
tf.reshape(x, shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[2, 5, 6],
       [7, 1, 8]], dtype=int32)>

In [ ]:
tf.reshape(x, shape=(2,3)) @ y

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[14, 27, 26],
       [23, 39, 39]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(x),y )

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 4, 13,  6],
       [21, 41, 37]], dtype=int32)>

In [ ]:
tf.matmul(tf.reshape(x,shape=(2,3)),y )

In [ ]:
print(x)
z =tf.cast(x, dtype=tf.float16)
z

In [ ]:
import numpy as np
T = tf.constant(np.random.randint(0,100,50))
T

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([71, 13, 98, 85, 85,  1, 87, 72, 63, 63, 37, 50, 64, 56, 39, 90, 28,
       96, 67,  3, 32, 11, 84, 93, 13, 16, 87, 49, 42, 50, 25, 93, 33, 18,
       88, 92, 27, 22, 42, 55, 26, 51, 56, 11, 65, 76, 43, 13, 38, 49])>

In [ ]:
tf.reduce_mean(T)


<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
T_float = tf.cast(T, dtype=tf.float32)
T_float

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([71., 13., 98., 85., 85.,  1., 87., 72., 63., 63., 37., 50., 64.,
       56., 39., 90., 28., 96., 67.,  3., 32., 11., 84., 93., 13., 16.,
       87., 49., 42., 50., 25., 93., 33., 18., 88., 92., 27., 22., 42.,
       55., 26., 51., 56., 11., 65., 76., 43., 13., 38., 49.],
      dtype=float32)>

In [ ]:
tf.math.reduce_std(T_float)


In [ ]:
tf.math.reduce_variance(T_float)

<tf.Tensor: shape=(), dtype=float32, numpy=801.75037>

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(T)

<tf.Tensor: shape=(), dtype=int64, numpy=801>